name = "adinq"
compatibility_date = "2025-10-16"

[[d1_databases]]
binding = "DB"
database_name = "adinq"
database_id = "07b19823-78d6-4d2b-b8e4-b9dc6c537091"

[[r2_buckets]]
binding = "FILES"
bucket_name = "adinq"
